name: Issue report
description: Report any problem here
labels: ["bug", "triage"]
body:
  - type: input
    id: board
    attributes:
      label: Board
      description: On which Board does this issue occur?
      placeholder: eg. ESP32 Dev Module, ESP32-S2, NodeMCU 1.0 (ESP-12E Module)...
    validations:
      required: true
  - type: textarea
    id: devboard
    attributes:
      label: Device Description
      description: What development board or other hardware is the chip attached to?
      placeholder: ex. DevKitC, plain module on breadboard, etc. If your hardware is custom or unusual, please attach a photo.
    validations:
       required: true
  - type: input
    id: arduino-esp32-version
    attributes:
      label: Arduino-ESP32 Version
      description: What version of Arduino ESP32 are you running? If possible, consider updating to the latest version.
    validations:
      required: true
  - type: input
    id: bytebeam-arduino-sdk-version
    attributes:
      label: Bytebeam Arduino SDK Version
      description: What version of Bytebeam Arduino SDK are you running? If possible, consider updating to the latest version.
    validations:
      required: true
  - type: input
    id: ide
    attributes:
     label: IDE Name
     description: What IDE are you using?
     placeholder: eg. Arduino IDE, PlatformIO...
    validations:
     required: true
  - type: input
    id: host-os
    attributes:
      label: Operating System
      description: On which OS does this issue occur?
      placeholder: ex. macOS 12.1, Windows 10...
    validations:
      required: true
  - type: textarea
    id: problem-escription
    attributes:
      label: Problem Description
      description: Please describe your problem here and expected behaviour
      placeholder: ex. Can't connect/weird behaviour/wrong function/missing parameter..
    validations:
      required: true
  - type: textarea
    id: sketch
    attributes:
      label: Sketch
      description: Please provide full minimal sketch/code which can be run to reproduce your issue
      placeholder: ex. Related part of the code to replicate the issue
      render: cpp
    validations:
     required: true
  - type: textarea
    id: Debug
    attributes:
      label: Debug Message
      description: Please provide a debug message or error message. If you have a Guru Meditation Error or Backtrace, please decode it with [ExceptionDecoder](https://github.com/me-no-dev/EspExceptionDecoder)
      placeholder: Enable SDK debug level - Use BytebeamLogger::LOG_DEBUG in begin method, then put the serial output here.
      render: plain
    validations:
      required: true      
  - type: textarea
    id: other-remarks
    attributes:
      label: More Information 
      description: Is there any other information you can think of which will help us reproduce this problem? Any additional info can be added as well.
      placeholder: ex. I also tried on other OS, HW...it works correctly on that setup.